/**
 * Projects Data - AUTO-GENERATED by tools/build.js — do not edit by hand.
 * Edit the markdown files in projects/ instead, then run: npm run build
 */

const rawProjects = [
  {
    "id": 1,
    "year": "2026",
    "team": "조윤하루",
    "members": "Kyeongmin Ha, Huiseo Yun, Yuna Cho",
    "title": "Surf Road: A Fusion of Personal and Shared Mobility for Seamless Urban Experience",
    "desc": "As personal mobility (PM) ridership surges, contemporary urban planning focuses heavily on dedicating isolated lanes, often overlooking the continuity of the seamless transit experience. To address these fragmented transfer points between public transit and micro-mobility, this paper introduces ‘Surf Road’, a novel paradigm in urban transportation. While modern cities are physically connected, a rider’s journey is often abruptly disrupted at the boundaries of macro-infrastructure. Accompanied by a video demonstration, we present a symbiotic PM system that organically docks with moving tram networks, transforming a stagnant commute into a playful, continuous 'urban surfing' experience. Without requiring prohibitive infrastructure overhauls, Surf Road seamlessly coexists with existing transit grids to deliver a high-continuity user experience (UX), offering a futuristic framework for human-infrastructure symbiosis.",
    "keywords": [
      "Micro-mobility",
      "Public Transit Symbiosis",
      "Urban Surfing",
      "Human-Infrastructure Interaction",
      "Playful Interaction"
    ],
    "thumb": "./assets/2026/thumbnails/surfroad.gif",
    "youtubeEmbed": "https://www.youtube.com/embed/uNRzjdjFuew?si=JqsMg8SQ--qNWgMk",
    "videoUrl": null,
    "gallery": [],
    "blogContent": "<p><strong>To Appear at:</strong> </p>\n<ul>\n<li>Adjunct Proceedings of the 18th International Conference on Automotive User Interfaces and Interactive Vehicular Applications (AutomotiveUI 2026)\n<a href=\"https://doi.org/10.1145/3828158.3833053\">doi.org/10.1145/3828158.3833053</a></li>\n</ul>\n",
    "materials": [
      {
        "type": "report",
        "label": "📄 Publication: AutomotiveUI'26 (PDF)",
        "url": "./assets/2026/pdf/surfroad-paper.pdf"
      }
    ]
  },
  {
    "id": 2,
    "year": "2025",
    "team": "Omega",
    "members": "Jiyeon Lee, Jiwon Kang, Gyeonghun Min",
    "title": "Reconfigurable Roadways: Envisioning the Future of V2X-Driven Autonomous Urban Infrastructure through an Interactive Tabletop Simulator",
    "desc": "Autonomous driving and cooperative platooning are expected to transform urban mobility, significantly reducing traffic density in populated cities. Therefore large portions of road infrastructure could become underutilized, presenting valuable opportunities for spatial reallocation. These spaces could host Tactical Urbanism strategies supporting socially adaptive, community-centered urban transformation. We introduce Reconfigurable Roadways (RR)—an adaptive system reallocating road space by expanding pedestrian zones and dynamically modulating vehicle flows through real-time demand. Using V2X-enabled traffic coordination, RR offers a scalable framework for highly flexible, multi-use streets. To illustrate RR and clarify current technology and diverse future possibilities, we present an interactive tabletop simulator of an urban mobility scene. The tangible simulator lets users rearrange modular blocks—each representing a roadway role—to explore near-future scenarios and observe simulated changes in traffic behavior and urban form. The platform fosters intuitive understanding of RR principles and engages users in shaping future urban mobility systems.",
    "keywords": [
      "Reconfigurable roadway",
      "Autonomous driving",
      "V2X",
      "Tactical urbanism"
    ],
    "thumb": "./assets/2025/thumbnails/FMDT-RR2025.gif",
    "youtubeEmbed": "https://www.youtube.com/embed/Cg66rUHUL18?si=59R_Bs-6TapHi7-8",
    "videoUrl": null,
    "gallery": [],
    "blogContent": "<p><strong>Published at:</strong> </p>\n<ul>\n<li>Adjunct Proceedings of the 17th International Conference on Automotive User Interfaces and Interactive Vehicular Applications (AutomotiveUI 2025)\n<a href=\"https://doi.org/10.1145/3744335.3756852\">doi.org/10.1145/3744335.3756852</a></li>\n</ul>\n",
    "materials": [
      {
        "type": "report",
        "label": "📄 Publication: AutomotiveUI'25 (PDF)",
        "url": "./assets/2025/pdf/RR-paper.pdf"
      }
    ]
  },
  {
    "id": 3,
    "year": "2025",
    "team": "소소한조",
    "members": "Hyeonjoon So, Eugene Han, Haon Jo",
    "title": "COCOON : Emotional Survival in the Age of Automated Care",
    "desc": "Cocoon is a speculative autonomous mobility system designed to support children in a future where traditional caregiving structures have collapsed. As birth rates decline and parental presence diminishes due to socioeconomic pressures, children are increasingly left to navigate daily life alone. Cocoon addresses this by offering a responsive, emotionally intelligent space that interacts through voice and gesture recognition. It features a transformable seating system, an omnidirectional treadmill, and a character-based interface that adapts to a child’s physical and emotional state. By incorporating affective computing and embodied interaction, Cocoon fosters a sense of companionship and autonomy during transit. Rather than replacing human care, the project critically explores what it means for technology to assume caregiving roles. Through scenario-based user flows and immersive storytelling, Cocoon presents a provocative design fiction that challenges conventional mobility paradigms and raises ethical questions about the automation of empathy and care in children’s everyday lives.",
    "keywords": [
      "Child-Centered UX",
      "Speculative Design",
      "Emotion-aware Interaction",
      "AI-drivenCare System"
    ],
    "thumb": "./assets/2025/thumbnails/cocoon.gif",
    "youtubeEmbed": "https://www.youtube.com/embed/wStp_WJrp7s?si=rC8gXZtWdUYevM-Y",
    "videoUrl": null,
    "gallery": [],
    "blogContent": "<p><strong>Published at:</strong> </p>\n<ul>\n<li>Adjunct Proceedings of the 17th International Conference on Automotive User Interfaces and Interactive Vehicular Applications (AutomotiveUI 2025)\n<a href=\"https://doi.org/10.1145/3744335.375685\">doi.org/10.1145/3744335.375685</a></li>\n</ul>\n",
    "materials": [
      {
        "type": "report",
        "label": "📄 Publication: AutomotiveUI'25 (PDF)",
        "url": "./assets/2025/pdf/cocoon-paper.pdf"
      }
    ]
  },
  {
    "id": 4,
    "year": "2025",
    "team": "보슷홍다이나믹스",
    "members": "Yongjun Kim, Jungho Kwon, Sojin Han",
    "title": "Taming XR Zombies: Proxemics-Aware Kinesthetic Feedback Interfaces for Safe Social Harmony in Autonomous Mobility Environments",
    "desc": "As extended reality (XR) technologies approach mainstream adoption in autonomous vehicles (AVs), passengers will engage in sustained immersive experiences throughout their journeys. However, when multiple passengers use XR headsets in confined vehicle spaces, this creates new challenges in physical safety and social dynamics due to compromised spatial awareness and movement interference. We present a proximity-aware kinesthetic constraint and adaptive XR interaction system that addresses both physical coordination and interaction design challenges. Grounded in proxemic theory, the system operates through progressive Open/Medium/Dense modes: dynamically constraining arm movement via elbow-to-waist and wrist-to-shoulder restrictions while simultaneously adapting XR interactions from grab to ray-casting to micro-gesture (thumb-based). The system includes an emergency shutdown for sudden vehicle motion changes, immediately releasing all physical constraints and pausing XR content. Our approach demonstrates a novel solution for maintaining both usable XR experiences and respectful personal space in shared autonomous mobility environments.",
    "keywords": [
      "XR",
      "Social Dynamics",
      "PhysicalConstraint",
      "Speculative Design"
    ],
    "thumb": "./assets/2025/thumbnails/XR.gif",
    "youtubeEmbed": "https://www.youtube.com/embed/LzG59gxcnp0?si=BzrP0c_5QA48VnII",
    "videoUrl": null,
    "gallery": [],
    "blogContent": "<p><strong>Published at:</strong> </p>\n<ul>\n<li>Adjunct Proceedings of the 17th International Conference on Automotive User Interfaces and Interactive Vehicular Applications (AutomotiveUI 2025)\n<a href=\"https://doi.org/10.1145/3744335.3758478\">doi.org/10.1145/3744335.3758478</a></li>\n<li>Proceedings of the 2025 31st ACM Symposium on Virtual Reality Software and Technology (VRST 2025)\n<a href=\"https://doi.org/10.1145/3756884.3768375\">doi.org/10.1145/3756884.3768375</a></li>\n</ul>\n",
    "materials": [
      {
        "type": "report",
        "label": "📄 Publication: AutomotiveUI'25 (PDF)",
        "url": "./assets/2025/pdf/zombie-paper.pdf"
      },
      {
        "type": "report",
        "label": "📄 Publication: VRST'25 (PDF)",
        "url": "./assets/2025/pdf/XR-paper.pdf"
      }
    ]
  },
  {
    "id": 5,
    "year": "2025",
    "team": "Aboard",
    "members": "Juang Lee, Yeonwoo Kang, Seongchan Nam, Soonbum Kwon",
    "title": "Reconfigurable Roadways: Envisioning the Future of V2X-Driven Autonomous Urban Infrastructure through an Interactive Tabletop Simulator",
    "desc": "As autonomous mobility approaches Level 4, we are now in a transitional phase shaped by fundamental changes in how passengers perceive safety, trust, and control. This study proposes a concept of multilevel feedback interface to alleviate passenger anxiety toward autonomous systems during this critical shift. The interface adopts a hybrid multilevel feedback approach, consisting of four distinct modes–Standby, Infotainment, Indicating, and Control–that respond to varying levels and sources of passenger anxiety through tactile and graphical cues. We present the concept, design process, and implementation of this interface, which aims to envision future autonomous mobility systems that are emotionally responsive, trust-enhancing, and passenger-centered.",
    "keywords": [
      "Reconfigurable roadway",
      "Autonomous driving",
      "V2X",
      "Tactical urbanism"
    ],
    "thumb": "./assets/2025/thumbnails/aboard.gif",
    "youtubeEmbed": "https://www.youtube.com/embed/nPMENpNphT0?si=UgvOibkXzlJzUiCu",
    "videoUrl": null,
    "gallery": [],
    "blogContent": "<p><strong>Published at:</strong> </p>\n<ul>\n<li>Adjunct Proceedings of the 17th International Conference on Automotive User Interfaces and Interactive Vehicular Applications (AutomotiveUI 2025)\n<a href=\"https://doi.org/10.1145/3744335.3756853\">doi.org/10.1145/3744335.3756853</a></li>\n</ul>\n",
    "materials": [
      {
        "type": "report",
        "label": "📄 Publication: AutomotiveUI'25 (PDF)",
        "url": "./assets/2025/pdf/aboard-paper.pdf"
      }
    ]
  }
];

const fallbackImage = "data:image/svg+xml;charset=UTF-8,%3Csvg width='600' height='400' xmlns='http://www.w3.org/2000/svg'%3E%3Crect width='100%25' height='100%25' fill='%23e2e8f0'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' font-family='sans-serif' font-size='20px' fill='%2364748b'%3EImage Not Found%3C/text%3E%3C/svg%3E";
